name: Module Runner

on:
    schedule:
        # run every 30 minutes
        #- cron: '0 20 */3 * *'
    #push:
        branches:
        - main

jobs:
    run:
        runs-on: ubuntu-latest
        timeout-minutes: 360
        steps:
        - name: Checkout
          uses: actions/checkout@v2
        
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.10.14'
        
        - name: Install dependencies
          run: |
            python3 -m pip install --upgrade pip
            pip install -r requirements.txt
        
        - name: Step 1 - Run pipe1 script
          run: python3 pipe1.py
          working-directory: ${{ github.workspace }}

        - name: Step 2 - Run pipe2 script
          run: python3 pipe2.py
          working-directory: ${{ github.workspace }}

        - name: Step 3 - Run Commit files
          run: |
            git config --local user.name "github-actions[bot]"
            git config --local user.email "76592342+github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "Github action Update $(date)"
            git push origin main
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
